export interface StateRule {
  stateName: string;
  maxPct: number;
  pl: 'none' | 'strong' | 'moderate' | 'federal';
  limitYrs: number;
  lawsuit: boolean;
  alt: string;
  notes: string;
  links: { l: string; url: string }[];
}

export const RULES: Record<string, StateRule> = {
  AL:{ stateName:"Alabama",        maxPct:25,  pl:'federal',  limitYrs:6,  lawsuit:true, alt:"Federal baseline — lesser of 25% of disposable earnings or amount over 30× federal minimum wage per week.",         notes:"Alabama follows federal garnishment limits. A court judgment is required before any wage withholding begins.", links:[{l:"Alabama Courts",url:"https://alacourt.gov/"},{l:"Alabama Legal Help",url:"https://www.alabamalegalhelp.org/"}]},
  AK:{ stateName:"Alaska",         maxPct:25,  pl:'federal',  limitYrs:3,  lawsuit:true, alt:"Federal baseline applies. Alaska follows the standard federal garnishment formula.",                                   notes:"Alaska follows the federal 25% cap. The 3-year limitation period is shorter than most states.", links:[{l:"Alaska Courts Self-Help",url:"https://courts.alaska.gov/shc/index.htm"},{l:"Alaska Legal Services",url:"https://alsc-law.org/"}]},
  AZ:{ stateName:"Arizona",        maxPct:25,  pl:'federal',  limitYrs:6,  lawsuit:true, alt:"Federal baseline — lesser of 25% of disposable earnings or amount over 30× the federal minimum wage per week.",      notes:"Arizona follows federal garnishment limits. A judgment must be obtained first. Arizona also allows bank account levies after judgment.", links:[{l:"Arizona Courts — Debt Collection",url:"https://www.azcourts.gov/selfservicecenter/Debt-Collection"},{l:"Community Legal Services AZ",url:"https://clsaz.org/"}]},
  AR:{ stateName:"Arkansas",       maxPct:25,  pl:'federal',  limitYrs:5,  lawsuit:true, alt:"Federal baseline applies. Arkansas follows the standard federal garnishment formula.",                                   notes:"Arkansas follows federal garnishment limits. A judgment is required. The 5-year limitation applies to most consumer debt claims.", links:[{l:"Arkansas Courts",url:"https://arcourts.gov/"},{l:"Legal Aid of Arkansas",url:"https://arlegalservices.org/"}]},
  CA:{ stateName:"California",     maxPct:25,  pl:'federal',  limitYrs:4,  lawsuit:true, alt:"Or the amount by which disposable earnings exceed 40× the state minimum wage ($16/hr) per week, whichever is less.",  notes:"California limits garnishment to the lesser of two formulas — more protective for minimum-wage earners. A court judgment is required.", links:[{l:"California Courts — Wage Garnishment",url:"https://www.courts.ca.gov/selfhelp-wagegarnishment.htm"},{l:"California DFPI — Consumer Resources",url:"https://dfpi.ca.gov/consumers/"}]},
  CO:{ stateName:"Colorado",       maxPct:25,  pl:'federal',  limitYrs:6,  lawsuit:true, alt:"Federal baseline applies. Certain income types (Social Security, public benefits) are fully exempt.",                 notes:"Colorado follows federal garnishment limits. A judgment is required for consumer debts. Benefit income receives additional protections.", links:[{l:"Colorado Judicial Branch",url:"https://www.courts.state.co.us/Self_Help/debtcollection.cfm"},{l:"Colorado Legal Services",url:"https://coloradolegalservices.org/"}]},
  CT:{ stateName:"Connecticut",    maxPct:25,  pl:'federal',  limitYrs:6,  lawsuit:true, alt:"The first $455 per week of disposable income is fully exempt. Above that threshold, up to 25% may be garnished.",    notes:"Connecticut provides a meaningful income-floor exemption protecting lower earners. A judgment is required before garnishment can begin.", links:[{l:"Connecticut Judicial Branch",url:"https://www.jud.ct.gov/"},{l:"Connecticut Legal Services",url:"https://ctlegal.org/"}]},
  DE:{ stateName:"Delaware",       maxPct:15,  pl:'strong',   limitYrs:3,  lawsuit:true, alt:"Delaware caps garnishment at 15% of disposable income — more protective than the federal 25% cap.",                  notes:"Delaware's 15% cap and short 3-year limitation period offer notable debtor protections. A court judgment is required.", links:[{l:"Delaware Courts Self-Help",url:"https://courts.delaware.gov/help/"},{l:"Community Legal Aid Society DE",url:"https://declasi.org/"}]},
  DC:{ stateName:"Washington D.C.",maxPct:25,  pl:'federal',  limitYrs:3,  lawsuit:true, alt:"Federal baseline applies. D.C. follows the standard 25% cap with exemptions for certain income types.",               notes:"D.C. follows federal garnishment limits. The 3-year limitation period is shorter than most states. A judgment is required.", links:[{l:"D.C. Courts — Debt Collection",url:"https://www.dccourts.gov/services/civil-matters/debt-collection"},{l:"D.C. Bar Pro Bono Center",url:"https://www.dcbar.org/pro-bono"}]},
  FL:{ stateName:"Florida",        maxPct:25,  pl:'federal',  limitYrs:5,  lawsuit:true, alt:"Head-of-household exemption may fully protect wages if you provide more than 50% of support for a dependent.",        notes:"Florida's head-of-household exemption can fully protect wages for qualifying individuals — but must be actively claimed. A court judgment is required.", links:[{l:"Florida Courts Self-Help",url:"https://www.flcourts.gov/Resources-Services/Court-Improvement/Family-Courts/Self-Help-Information"},{l:"Florida Bar — Find a Lawyer",url:"https://www.floridabar.org/public/ris/"}]},
  GA:{ stateName:"Georgia",        maxPct:25,  pl:'federal',  limitYrs:6,  lawsuit:true, alt:"Federal baseline — lesser of 25% of disposable earnings or amount over 30× the federal minimum wage per week.",       notes:"A court judgment is required before garnishment in Georgia. Judgments can be renewed and remain enforceable up to 7 years. Medical debt is treated like any other consumer debt.", links:[{l:"Georgia Legal Aid — Garnishment",url:"https://www.georgialegalaid.org/resource/wage-garnishment"},{l:"Georgia Courts",url:"https://georgiacourts.gov/"}]},
  HI:{ stateName:"Hawaii",         maxPct:5,   pl:'strong',   limitYrs:6,  lawsuit:true, alt:"Tiered formula: 5% of first $100/month, 10% of next $100, up to 20% above that — far below the federal cap.",        notes:"Hawaii's tiered formula makes it one of the most protective states. Most low-to-moderate earners see very little garnished. A judgment is required.", links:[{l:"Hawaii Judiciary Self-Help",url:"https://www.courts.state.hi.us/self-help_center/self-help_center"},{l:"Legal Aid Society of Hawaii",url:"https://www.legalaidhawaii.org/"}]},
  ID:{ stateName:"Idaho",          maxPct:25,  pl:'federal',  limitYrs:5,  lawsuit:true, alt:"Federal baseline applies. Idaho follows the standard 25% cap on disposable earnings.",                                 notes:"Idaho follows federal garnishment limits. A court judgment is required. Idaho also allows bank account levies after judgment.", links:[{l:"Idaho Courts Self-Help",url:"https://isc.idaho.gov/pages/self-help"},{l:"Idaho Legal Aid Services",url:"https://www.idaholegalaid.org/"}]},
  IL:{ stateName:"Illinois",       maxPct:15,  pl:'strong',   limitYrs:5,  lawsuit:true, alt:"Or the amount by which net wages exceed 45× the federal minimum wage per week — significantly more protective than the federal 25% cap.", notes:"Illinois caps garnishment at 15% of gross wages — far lower than federal law. Low-income exemptions may also apply. A judgment is required.", links:[{l:"Illinois Legal Aid — Wage Garnishment",url:"https://www.illinoislegalaid.org/legal-information/wage-garnishment"},{l:"Illinois Courts Self-Help",url:"https://illinoiscourts.gov/self-help/"}]},
  IN:{ stateName:"Indiana",        maxPct:25,  pl:'federal',  limitYrs:6,  lawsuit:true, alt:"Federal baseline applies. Indiana follows the standard federal garnishment formula.",                                   notes:"Indiana follows federal garnishment limits. A court judgment is required. Certain public benefit income is exempt from garnishment.", links:[{l:"Indiana Courts Self-Help",url:"https://www.in.gov/courts/selfservice/"},{l:"Indiana Legal Services",url:"https://www.indianalegalservices.org/"}]},
  IA:{ stateName:"Iowa",           maxPct:25,  pl:'federal',  limitYrs:5,  lawsuit:true, alt:"Federal baseline applies. Iowa also provides exemptions for earnings needed to support a family.",                      notes:"Iowa follows federal garnishment limits. A judgment is required. Iowa provides some family-support exemptions that may reduce garnishable amounts.", links:[{l:"Iowa Courts — Money Issues",url:"https://www.iowacourts.gov/for-the-public/court-forms-information/for-money-issues/"},{l:"Iowa Legal Aid",url:"https://www.iowalegalaid.org/"}]},
  KS:{ stateName:"Kansas",         maxPct:25,  pl:'federal',  limitYrs:5,  lawsuit:true, alt:"Federal baseline applies. Kansas follows the standard federal garnishment formula.",                                   notes:"Kansas follows federal garnishment limits. A court judgment is required. Social Security, unemployment, and other benefit income cannot be garnished.", links:[{l:"Kansas Courts Self-Help",url:"https://www.kscourts.org/Kansas-Courts/Self-Help-Resources/default.aspx"},{l:"Kansas Legal Services",url:"https://www.kansaslegalservices.org/"}]},
  KY:{ stateName:"Kentucky",       maxPct:25,  pl:'federal',  limitYrs:5,  lawsuit:true, alt:"Federal baseline applies. Kentucky follows the standard 25% cap on disposable earnings.",                             notes:"Kentucky follows federal garnishment limits. A court judgment is required. Social Security and similar income is exempt from garnishment.", links:[{l:"Kentucky Courts Self-Help",url:"https://courts.ky.gov/resources/publicationsresources/Pages/Court-Guides.aspx"},{l:"Kentucky Legal Aid",url:"https://www.klaid.org/"}]},
  LA:{ stateName:"Louisiana",      maxPct:25,  pl:'federal',  limitYrs:3,  lawsuit:true, alt:"The first $254 per week of disposable income is exempt from garnishment in Louisiana.",                                notes:"Louisiana provides a $254/week floor exemption protecting lower earners. Above that, up to 25% may be garnished. The 3-year limitation period is relatively short. A judgment is required.", links:[{l:"Louisiana Courts Self-Help",url:"https://www.lacourt.org/"},{l:"Southeast Louisiana Legal Services",url:"https://slls.org/"}]},
  ME:{ stateName:"Maine",          maxPct:25,  pl:'federal',  limitYrs:6,  lawsuit:true, alt:"Federal baseline applies. Maine follows the standard 25% cap with some income-based protections for lower earners.",   notes:"Maine follows federal garnishment limits. A judgment is required. Maine provides some protections for low-income earners and exempt income types.", links:[{l:"Maine Courts Self-Help",url:"https://www.courts.maine.gov/self_help/civil/small_claims.html"},{l:"Pine Tree Legal Assistance",url:"https://www.ptla.org/"}]},
  MD:{ stateName:"Maryland",       maxPct:25,  pl:'federal',  limitYrs:3,  lawsuit:true, alt:"Federal baseline applies, but the first $145 per week of net wages is fully exempt from garnishment.",                notes:"Maryland provides a $145/week floor exemption. The short 3-year limitation period offers some protection against old debts. A judgment is required before garnishment.", links:[{l:"Maryland Courts — Wage Garnishment",url:"https://www.courts.state.md.us/district/forms/civil/dcdistrictcourtforms.html"},{l:"Maryland Legal Aid",url:"https://www.mdlab.org/"}]},
  MA:{ stateName:"Massachusetts",  maxPct:15,  pl:'strong',   limitYrs:6,  lawsuit:true, alt:"Massachusetts caps wage garnishment at 15% of gross wages — significantly more protective than the federal 25% cap.",  notes:"Massachusetts limits garnishment to 15% of gross wages with additional protections for low-income earners. A judgment is required.", links:[{l:"Massachusetts — Wage Garnishment Guide",url:"https://www.mass.gov/guides/wage-garnishment"},{l:"Greater Boston Legal Services",url:"https://www.gbls.org/"}]},
  MI:{ stateName:"Michigan",       maxPct:25,  pl:'federal',  limitYrs:6,  lawsuit:true, alt:"Federal baseline applies. Very low-income earners may be protected by additional state exemptions.",                   notes:"Michigan follows federal garnishment limits. A judgment is required. Very low-income earners may be protected by additional state exemptions.", links:[{l:"Michigan Legal Help — Garnishment",url:"https://michiganlegalhelp.org/self-help-tools/money-and-debt/garnishment"},{l:"Michigan Legal Help",url:"https://michiganlegalhelp.org/"}]},
  MN:{ stateName:"Minnesota",      maxPct:25,  pl:'federal',  limitYrs:6,  lawsuit:true, alt:"Or the amount by which disposable earnings exceed 40× the state minimum wage ($10.85/hr) per week, whichever is less.", notes:"Minnesota's alternative formula provides meaningful protection for minimum-wage earners. A judgment is required before any garnishment.", links:[{l:"Minnesota Courts — Garnishment",url:"https://www.mncourts.gov/GetForms.aspx?c=17"},{l:"Southern MN Regional Legal Services",url:"https://www.smrls.org/"}]},
  MS:{ stateName:"Mississippi",    maxPct:25,  pl:'federal',  limitYrs:3,  lawsuit:true, alt:"Federal baseline applies. Mississippi follows the standard federal garnishment formula.",                               notes:"Mississippi follows federal garnishment limits. The 3-year limitation period is shorter than many states. A judgment is required before any wage garnishment.", links:[{l:"Mississippi Courts",url:"https://courts.ms.gov/"},{l:"MS Center for Legal Services",url:"https://mscenterforlegalservices.org/"}]},
  MO:{ stateName:"Missouri",       maxPct:25,  pl:'federal',  limitYrs:5,  lawsuit:true, alt:"Federal baseline applies. Missouri follows the standard federal garnishment formula.",                                   notes:"Missouri follows federal garnishment limits. A court judgment is required. The 5-year statute of limitations applies to most consumer contract debts.", links:[{l:"Missouri Courts Self-Help",url:"https://www.courts.mo.gov/page.jsp?id=302"},{l:"Legal Services of Eastern Missouri",url:"https://lsem.org/"}]},
  MT:{ stateName:"Montana",        maxPct:25,  pl:'federal',  limitYrs:5,  lawsuit:true, alt:"Federal baseline applies. Montana follows the standard federal garnishment formula.",                                   notes:"Montana follows federal garnishment limits. A judgment is required. Montana provides additional exemptions for certain personal property and income types.", links:[{l:"Montana Courts Self-Help",url:"https://courts.mt.gov/self-help"},{l:"Montana Legal Services Association",url:"https://www.mtlsa.org/"}]},
  NE:{ stateName:"Nebraska",       maxPct:15,  pl:'strong',   limitYrs:5,  lawsuit:true, alt:"Nebraska caps garnishment at 15% of disposable income — more protective than the federal 25% cap.",                   notes:"Nebraska limits garnishment to 15% of disposable earnings. A court judgment is required. Exempt income types include Social Security and unemployment.", links:[{l:"Nebraska Judicial Branch Self-Help",url:"https://supremecourt.nebraska.gov/self-help"},{l:"Nebraska Legal Aid",url:"https://www.nebraskalegalaid.org/"}]},
  NV:{ stateName:"Nevada",         maxPct:25,  pl:'federal',  limitYrs:6,  lawsuit:true, alt:"Or the amount by which disposable earnings exceed 50× the federal minimum wage per week — a very protective alternative formula.", notes:"Nevada's 50× minimum wage alternative formula provides substantial protection for many earners. Nevada also has strong homestead and personal property exemptions. A judgment is required.", links:[{l:"Nevada Courts Self-Help",url:"https://www.nevadajudiciary.us/index.php/selfhelp"},{l:"Nevada Legal Services",url:"https://nlslaw.net/"}]},
  NH:{ stateName:"New Hampshire",  maxPct:25,  pl:'federal',  limitYrs:3,  lawsuit:true, alt:"Federal baseline applies. New Hampshire follows the standard federal garnishment formula.",                             notes:"New Hampshire follows federal garnishment limits. The 3-year limitation period is relatively short. A judgment is required before any wage garnishment.", links:[{l:"New Hampshire Courts Self-Help",url:"https://www.courts.nh.gov/self-help"},{l:"NH Legal Assistance",url:"https://www.nhla.org/"}]},
  NJ:{ stateName:"New Jersey",     maxPct:10,  pl:'strong',   limitYrs:6,  lawsuit:true, alt:"New Jersey caps garnishment at 10% of gross wages per pay period — among the lowest caps in the country.",             notes:"New Jersey's 10% gross-wage cap makes it one of the most debtor-protective states for employed workers. A court judgment is required.", links:[{l:"New Jersey Courts — Debt Collection",url:"https://www.njcourts.gov/self-help/debt-collection.html"},{l:"Legal Services of New Jersey",url:"https://www.lsnj.org/"}]},
  NM:{ stateName:"New Mexico",     maxPct:25,  pl:'federal',  limitYrs:6,  lawsuit:true, alt:"Federal baseline applies. New Mexico follows the standard federal garnishment formula.",                               notes:"New Mexico follows federal garnishment limits. A court judgment is required. The state provides additional exemptions for certain public benefit income.", links:[{l:"New Mexico Courts Self-Help",url:"https://nmcourts.gov/self-help-center/"},{l:"New Mexico Legal Aid",url:"https://www.newmexicolegalaid.org/"}]},
  NY:{ stateName:"New York",       maxPct:10,  pl:'strong',   limitYrs:6,  lawsuit:true, alt:"New York caps garnishment at 10% of gross wages or 25% of disposable earnings, whichever is less.",                   notes:"New York's 10% gross-wage cap is far more protective than the federal 25% standard. A judgment is required. Additional income-based exemptions may further reduce exposure.", links:[{l:"NY Courts — Enforcement of Judgments",url:"https://www.nycourts.gov/courthelp/financial/garnishment.shtml"},{l:"Legal Aid Society NYC",url:"https://legalaidnyc.org/"}]},
  NC:{ stateName:"North Carolina", maxPct:0,   pl:'none',     limitYrs:3,  lawsuit:true, alt:"Wage garnishment is prohibited for most private consumer debts, including medical bills and credit cards.",             notes:"One of the most debtor-protective states. Even after a creditor obtains a judgment, wages generally cannot be garnished for consumer debts. Creditors can still levy bank accounts or place property liens.", links:[{l:"NC Courts — Debt Collection",url:"https://www.nccourts.gov/help-topics/money-and-debt/debt-collection"},{l:"Legal Aid NC",url:"https://www.legalaidnc.org/"}]},
  ND:{ stateName:"North Dakota",   maxPct:25,  pl:'federal',  limitYrs:6,  lawsuit:true, alt:"Federal baseline applies. North Dakota follows the standard federal garnishment formula.",                             notes:"North Dakota follows federal garnishment limits. A court judgment is required. The state provides exemptions for certain personal property and income types.", links:[{l:"North Dakota Courts Self-Help",url:"https://www.ndcourts.gov/legal-self-help"},{l:"Legal Services of North Dakota",url:"https://www.legalassist.org/"}]},
  OH:{ stateName:"Ohio",           maxPct:25,  pl:'federal',  limitYrs:6,  lawsuit:true, alt:"Federal baseline — lesser of 25% of disposable earnings or the amount exceeding 30× the federal minimum wage per week.", notes:"Ohio follows federal garnishment limits. A court judgment must be obtained first. After judgment, creditors can also levy bank accounts.", links:[{l:"Ohio Legal Help — Wage Garnishment",url:"https://www.ohiolegalhelp.org/topic/wage-garnishment"},{l:"Ohio Supreme Court Self-Help",url:"https://www.supremecourt.ohio.gov/"}]},
  OK:{ stateName:"Oklahoma",       maxPct:25,  pl:'federal',  limitYrs:5,  lawsuit:true, alt:"Federal baseline applies. Oklahoma also provides head-of-household wage protections in certain circumstances.",         notes:"Oklahoma follows federal garnishment limits. A judgment is required. Head-of-household exemptions may apply in some circumstances.", links:[{l:"Legal Aid Services of Oklahoma",url:"https://www.legalaidok.org/"},{l:"Oklahoma Courts",url:"https://www.oscn.net/"}]},
  OR:{ stateName:"Oregon",         maxPct:25,  pl:'federal',  limitYrs:6,  lawsuit:true, alt:"Or the amount by which disposable earnings exceed 40× the state minimum wage ($14.20/hr) per week, whichever is less.", notes:"Oregon's alternative formula based on the state minimum wage provides additional protection for lower-wage earners. A judgment is required before any garnishment.", links:[{l:"Oregon Courts Self-Help",url:"https://www.courts.oregon.gov/help/Pages/default.aspx"},{l:"Oregon Law Help",url:"https://oregonlawhelp.org/"}]},
  PA:{ stateName:"Pennsylvania",   maxPct:0,   pl:'none',     limitYrs:4,  lawsuit:true, alt:"Wage garnishment is prohibited for most private consumer debts. Wages are protected except for taxes, child support, and certain federal student loans.", notes:"Pennsylvania offers among the strongest wage protections in the country. After a judgment, creditors cannot garnish wages for consumer debts — but bank account levies and property liens remain possible.", links:[{l:"PA Legal Aid Network",url:"https://palegalaid.net/"},{l:"Pennsylvania Courts Self-Help",url:"https://www.pacourts.us/learn/representing-yourself"}]},
  RI:{ stateName:"Rhode Island",   maxPct:25,  pl:'federal',  limitYrs:10, lawsuit:true, alt:"The first $50 per week is exempt; thereafter, up to 25% of disposable income may be garnished.",                       notes:"Rhode Island follows federal limits. The 10-year statute of limitations is among the longest in the country — meaning old debts remain actionable for a long time. A judgment is required.", links:[{l:"Rhode Island Courts Self-Help",url:"https://www.courts.ri.gov/PublicResources/selfhelp/Pages/default.aspx"},{l:"Rhode Island Legal Services",url:"https://www.rils.org/"}]},
  SC:{ stateName:"South Carolina", maxPct:0,   pl:'none',     limitYrs:3,  lawsuit:true, alt:"Wage garnishment is prohibited for most private consumer debts in South Carolina.",                                    notes:"South Carolina prohibits wage garnishment for most private consumer debts. Even after a judgment, wages cannot be garnished. However, bank levies and property liens remain available to creditors.", links:[{l:"South Carolina Courts",url:"https://www.sccourts.org/selfHelp/"},{l:"SC Legal Services",url:"https://www.sclegal.org/"}]},
  SD:{ stateName:"South Dakota",   maxPct:20,  pl:'moderate', limitYrs:6,  lawsuit:true, alt:"South Dakota caps garnishment at 20% of disposable earnings — below the federal 25% cap.",                            notes:"South Dakota caps garnishment at 20% of disposable earnings. A court judgment is required. The state provides some additional exemptions for personal income.", links:[{l:"South Dakota Courts",url:"https://ujs.sd.gov/Self-Help/"},{l:"East River Legal Services",url:"https://www.eastriverlegalservices.org/"}]},
  TN:{ stateName:"Tennessee",      maxPct:25,  pl:'federal',  limitYrs:6,  lawsuit:true, alt:"Federal baseline applies. Tennessee follows the standard federal garnishment formula.",                                 notes:"Tennessee follows federal garnishment limits. A court judgment is required. Additional income protections exist for very low earners and certain benefit recipients.", links:[{l:"Tennessee Courts Self-Help",url:"https://www.tncourts.gov/help-center"},{l:"Tennessee Alliance for Legal Services",url:"https://www.tals.org/"}]},
  TX:{ stateName:"Texas",          maxPct:0,   pl:'none',     limitYrs:4,  lawsuit:true, alt:"Texas prohibits wage garnishment for most private consumer debts, including medical bills, credit cards, and personal loans.", notes:"Texas is one of the most debtor-friendly states. Consumer creditors cannot garnish wages even after winning a judgment. However, bank account levies and property liens remain available to creditors.", links:[{l:"Texas Law Help — Debt Collection",url:"https://texaslawhelp.org/article/wage-garnishment"},{l:"Texas State Law Library",url:"https://www.sll.texas.gov/self-help/consumer-protection/"}]},
  UT:{ stateName:"Utah",           maxPct:25,  pl:'federal',  limitYrs:6,  lawsuit:true, alt:"Federal baseline applies. Utah follows the standard federal garnishment formula.",                                     notes:"Utah follows federal garnishment limits. A court judgment is required. Utah provides exemptions for retirement funds and certain personal property.", links:[{l:"Utah Courts Self-Help",url:"https://www.utcourts.gov/selfhelp/"},{l:"Utah Legal Services",url:"https://utahlegalservices.org/"}]},
  VT:{ stateName:"Vermont",        maxPct:25,  pl:'federal',  limitYrs:6,  lawsuit:true, alt:"Federal baseline applies with additional income-based exemptions for low-wage earners.",                               notes:"Vermont follows federal garnishment limits. The state provides additional income-based exemptions that can protect low-wage earners. A court judgment is required.", links:[{l:"Vermont Courts Self-Help",url:"https://www.vermontjudiciary.org/self-help"},{l:"Vermont Legal Aid",url:"https://www.vtlegalaid.org/"}]},
  VA:{ stateName:"Virginia",       maxPct:25,  pl:'federal',  limitYrs:5,  lawsuit:true, alt:"Federal baseline applies. Virginia follows the standard federal garnishment formula.",                                 notes:"Virginia follows federal garnishment limits. A judgment is required before garnishment. Virginia allows up to 5 garnishment liens simultaneously on the same debtor.", links:[{l:"Virginia Courts Self-Help",url:"https://selfhelp.vacourts.gov/"},{l:"Virginia Legal Aid",url:"https://www.valegalaid.org/"}]},
  WA:{ stateName:"Washington",     maxPct:25,  pl:'federal',  limitYrs:6,  lawsuit:true, alt:"Or the amount by which disposable earnings exceed 35× the state minimum wage per week, whichever is less.",           notes:"Washington state follows federal limits with income-based protections. A court judgment is required before any garnishment. Low-income exemptions may apply.", links:[{l:"Washington Courts — Garnishment",url:"https://www.courts.wa.gov/"},{l:"Northwest Justice Project",url:"https://nwjustice.org/"}]},
  WV:{ stateName:"West Virginia",  maxPct:20,  pl:'moderate', limitYrs:10, lawsuit:true, alt:"West Virginia caps garnishment at 20% of disposable earnings — below the federal 25% cap.",                           notes:"West Virginia's 20% cap provides slightly more protection than federal law. The 10-year limitation period is among the longest in the U.S. — debts remain actionable for a long time. A judgment is required.", links:[{l:"West Virginia Courts Self-Help",url:"https://courtswv.gov/help-center/self-represented-litigants"},{l:"West Virginia Legal Aid",url:"https://www.lawv.net/"}]},
  WI:{ stateName:"Wisconsin",      maxPct:20,  pl:'moderate', limitYrs:6,  lawsuit:true, alt:"Wisconsin caps garnishment at 20% of disposable earnings — below the federal 25% cap.",                              notes:"Wisconsin limits garnishment to 20% of disposable earnings. A court judgment is required. Wisconsin also provides additional head-of-household protections in some circumstances.", links:[{l:"Wisconsin Courts Self-Help",url:"https://www.wicourts.gov/services/public/selfhelp/"},{l:"Wisconsin Legal Aid",url:"https://www.lawshelp.org/"}]},
  WY:{ stateName:"Wyoming",        maxPct:25,  pl:'federal',  limitYrs:8,  lawsuit:true, alt:"Federal baseline applies. Wyoming follows the standard federal garnishment formula.",                                  notes:"Wyoming follows federal garnishment limits. The 8-year statute of limitations is longer than most states. A court judgment is required before any wage garnishment begins.", links:[{l:"Wyoming Courts Self-Help",url:"https://www.courts.state.wy.us/Resources/SelfHelp"},{l:"Wyoming Legal Services",url:"https://wyolegalservices.org/"}]},
};

export const FAQ_DATA: { q: string; a: string }[] = [
  { q:"Can a creditor garnish my wages without suing me first?", a:"For most private consumer debts — including medical bills, credit cards, and personal loans — a creditor must sue you and obtain a court judgment before garnishing wages. However, government debts (federal taxes, federal student loans, child support) can sometimes be garnished without a court order." },
  { q:"How long does a creditor have to sue me for medical debt?", a:"The statute of limitations varies by state, typically 3–6 years for medical debt. After this period, the debt is 'time-barred' — creditors can no longer successfully sue you, though they may still attempt collection. Making a payment or acknowledging a time-barred debt in writing can restart the clock in some states." },
  { q:"Which states prohibit wage garnishment for most consumer debt?", a:"Texas, Pennsylvania, North Carolina, and South Carolina broadly prohibit wage garnishment for most private consumer debts. Even in these states, federal taxes, child support, alimony, and federal student loans may still be garnished. Creditors can also pursue bank levies or property liens." },
  { q:"Can a garnishment be stopped once it starts?", a:"Yes, through several avenues: (1) Filing for bankruptcy triggers an automatic stay halting most garnishments immediately. (2) Negotiating a settlement or payment plan directly with the creditor. (3) Claiming an available exemption such as Florida's head-of-household protection. (4) Showing the underlying judgment was improperly obtained. An attorney can advise which option fits." },
  { q:"What's the difference between wage garnishment and a bank levy?", a:"Wage garnishment takes a percentage of your paycheck before you receive it — your employer sends it directly to the creditor. A bank levy freezes and seizes funds already in your bank account. Both require a court judgment for private consumer debts. States that protect wages (TX, PA, NC, SC) may still allow bank levies, which is why those states are not completely risk-free." },
  { q:"Does medical debt still affect my credit score?", a:"As of 2023, the three major credit bureaus removed all medical debt under $500 and stopped reporting paid medical debt. The CFPB has also proposed rules to eliminate most remaining medical debt from credit reports. However, unpaid medical debt over $500 can still appear on your credit report under current rules. Always verify directly with the bureaus." },
  { q:"Can I negotiate medical debt before a lawsuit is filed?", a:"Yes — and it's often your strongest position. Hospitals and medical providers frequently settle for less than the full balance, particularly when financial hardship is demonstrated. Many nonprofit hospitals are legally required to offer charity care. Always request an itemized bill first to check for billing errors, which are common in medical billing." },
  { q:"What protections do I have as head of household?", a:"Several states — most notably Florida — offer a head-of-household exemption that can fully or substantially protect wages if you provide more than half the financial support for a dependent. This exemption must be affirmatively claimed in your written response to the garnishment notice. Acting quickly within the response window is essential." },
];

export const SORTED_STATES = Object.entries(RULES).sort((a, b) =>
  a[1].stateName.localeCompare(b[1].stateName)
);
